##########
# Downloads & compiles create-react-app, saving built app to shared volume
###########

FROM node

WORKDIR /app

RUN git clone https://github.com/tiburon-security/petrichor-dashboard.git .

WORKDIR app

RUN yarn

RUN yarn build